<h1> Category </h1>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Key</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
        
        <?php  
        
            foreach ($category as $item) {
                echo "<tr>"
                . "<td>{$item->getId()}</td>"
                . "<td>{$item->getCategoryKey()}</td>"
                . "<td>{$item->getCategoryName()}</td>"
                . '<td><a href="'.$this->url('admin/category', array('action' => 'edit', 'id' => $item->getId())).'">Edit</a>&nbsp;&nbsp;'
                    . '<a href="'.$this->url('admin/category', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Are you sure you want to delete this record?\')) {document.location = this.href; } return false;">Delete</a></td>'
                . "</tr>"; 
                
                
            }
        
        ?>
    </tbody>
</table> 